### Specify Data type while creating Numpy Array

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40], dtype='i8')

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr = np.array([10, 20, 30, 40], dtype='i1')

In [6]:
arr.dtype

dtype('int8')

In [7]:
arr = np.array([10, 20, 30, 40])

In [8]:
arr.dtype

dtype('int32')

In [9]:
arr = np.array([10.5, 11.6, 12.3])

In [10]:
arr.dtype

dtype('float64')

In [11]:
arr = np.array([10.5, 11.6, 12.3], dtype='f8')

In [12]:
arr.dtype

dtype('float64')

In [14]:
arr = np.array([10.5, 11.6, 12.3], dtype='f4')

In [15]:
arr.dtype

dtype('float32')

### Converting Data Type for Numpy Array

In [21]:
arr = np.array([10, 20, 30])
arr.dtype
arr = arr.astype('float32')
arr
arr.dtype

dtype('float32')

### Ways to create Numpy Array

#### 1. From List/ Tuple (object(s) implementing array interface)

In [22]:
l = [10,20,30,40]
arr = np.array(l)

In [23]:
arr.dtype

dtype('int32')

In [24]:
t = (10,20,30,40)
arr = np.array(t)

In [25]:
arr.dtype

dtype('int32')

#### 2. By using numpy library functions

In [26]:
arr1 = np.zeros(5)

In [27]:
arr1

array([0., 0., 0., 0., 0.])

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2 = np.ones(5)

In [30]:
arr2

array([1., 1., 1., 1., 1.])

In [31]:
arr3 = np.full(5, 6)

In [32]:
arr3

array([6, 6, 6, 6, 6])

In [35]:
arr3 = np.full((2,3), 6)

In [36]:
arr3

array([[6, 6, 6],
       [6, 6, 6]])

In [37]:
arr3 = np.full([2,3], 6)

In [38]:
arr3

array([[6, 6, 6],
       [6, 6, 6]])

In [39]:
arr4 = np.arange(0,10,2)

In [40]:
arr4

array([0, 2, 4, 6, 8])

#### 3. From CSV and Txt Files

In [43]:
arr = np.genfromtxt("data.csv", delimiter=",")

In [44]:
arr

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [45]:
arr.dtype

dtype('float64')

### Operations with Numpy Arrays:

In [46]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,4,3])

#### 1. Math Oprs:

In [47]:
arr1 + arr2

array([3, 6, 6])

In [48]:
arr1 - arr2

array([-1, -2,  0])

In [49]:
arr1 * arr2

array([2, 8, 9])

In [50]:
arr1/arr2

array([0.5, 0.5, 1. ])

In [51]:
arr1 ** arr2

array([ 1, 16, 27])

In [53]:
arr1 ** 3 # vectorization support by numpy array

array([ 1,  8, 27], dtype=int32)

#### 2. Logical Operations

In [54]:
arr1 == arr2

array([False, False,  True])

In [55]:
arr1 > arr2

array([False, False, False])

In [56]:
np.logical_and(arr1, arr2)

array([ True,  True,  True])

In [57]:
arr2 = np.array([0,2,0])

In [58]:
np.logical_and(arr1, arr2)

array([False,  True, False])

#### 3. Statistical Operation on Numpy Array

In [59]:
arr1 = np.array([10,20,30,40,50,60])

In [60]:
np.sum(arr1)

210

In [61]:
np.mean(arr1)

35.0

In [62]:
np.median(arr1)

35.0

In [63]:
np.min(arr1)

10

In [64]:
np.max(arr1)

60

#### Slicing and Indexing

In [65]:
arr1 = np.array([10,20,30,40,50,60])

In [66]:
arr1[0]

10

In [68]:
arr1[-1]

60

In [69]:
arr1[0:4]

array([10, 20, 30, 40])

In [70]:
arr1[0:6:2]

array([10, 30, 50])

In [71]:
arr1[::2]

array([10, 30, 50])

In [72]:
arr1[::-1]

array([60, 50, 40, 30, 20, 10])

#### Reshaping and Manipulation with Numpy array

In [73]:
arr1 = np.array([10,20,30,40])

In [74]:
np.reshape(arr1, (2,2))

array([[10, 20],
       [30, 40]])

In [75]:
np.reshape(arr1, [2,2])

array([[10, 20],
       [30, 40]])

In [78]:
arr1 = np.array([[1, 2], [3, 4]])

In [79]:
arr1

array([[1, 2],
       [3, 4]])

In [80]:
arr1.T

array([[1, 3],
       [2, 4]])

In [81]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

In [84]:
np.concatenate((arr1, arr2), axis=0)

array([10, 20, 30, 40, 50, 60])

### Numpy Array attributes:

In [91]:
import numpy as np

# Create a numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Print the array attributes
print("Number of array dimensions:", arr.ndim)
print("Array shape:", arr.shape)
print("Total number of elements:", arr.size)
print("Data type of elements:", arr.dtype)
print("Size of each element (in bytes):", arr.itemsize)
print("Total size of the array (in bytes):", arr.nbytes)
print("Transposed array:\n", arr.T)


Number of array dimensions: 2
Array shape: (2, 3)
Total number of elements: 6
Data type of elements: int32
Size of each element (in bytes): 4
Total size of the array (in bytes): 24
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]


### Indexing and Slicing with Multi-dim Numpy array

In [92]:
import numpy as np

# Create a 2D numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# # Access the element in the second row and third column
# print(arr[1, 2])  # Output: 6

# # Slice the first row of the array
# print(arr[0, :])  # Output: [1 2 3]

# # Slice the second column of the array
# print(arr[:, 1])  # Output: [2 5]

In [93]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
arr.ndim

2

In [95]:
arr.shape

(2, 3)

In [96]:
# Index access in multi-dim array 
arr[0, 1] #2

2

In [97]:
# Slice on multi-dim array
arr[0, :]

array([1, 2, 3])

In [98]:
arr[:, 2]

array([3, 6])

### Broadcasting with Numpy Array

In [99]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [100]:
arr2 = np.array([10,20,30])

In [101]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
arr2

array([10, 20, 30])

In [103]:
res_arr = arr1 * arr2

In [104]:
res_arr

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [105]:
arr2 * 10

array([100, 200, 300])

### Looping through Numpy Array

#### 1. By using simple for loop

In [106]:
arr1 = np.array([10,20,30,40])

In [107]:
for entry in arr1:
    print(entry)

10
20
30
40


#### 2. By using nditer

In [109]:
for entry in np.nditer(arr1):
    print(entry)

10
20
30
40


#### 3. With ndenumerate()

In [111]:
for i, entry in np.ndenumerate(arr1):
    print(f"Index of element: {i} and element {entry}")

Index of element: (0,) and element 10
Index of element: (1,) and element 20
Index of element: (2,) and element 30
Index of element: (3,) and element 40


### Dot product of numpy arrays:

In [112]:
import numpy as np

In [113]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2 = np.array([[1,2,3], [2,3,3], [4,5,5]])

In [114]:
dot_arr = np.dot(arr1, arr2)

In [115]:
dot_arr

array([[17, 23, 24],
       [38, 53, 57],
       [59, 83, 90]])