In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3], [4,5,6]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
row_sums = np.sum(arr, axis=1)

In [5]:
row_sums

array([ 6, 15])

#### Binary Condition

In [6]:
a = np.array([1,2,3,4,5])
b = a > 3

In [7]:
b

array([False, False, False,  True,  True])

#### View

In [15]:
a = np.array([1,2,3])
b = a[1:]
b[0] = 4
print(b)
print(a)

[4 3]
[1 4 3]


#### Copy

In [22]:
a = np.array([1,2,3])
b = a.copy()
print(a)
print(b)
b[1] = 4
print(a)
print(b)

[1 2 3]
[1 2 3]
[1 2 3]
[1 4 3]


#### Sorting

In [23]:
arr = np.array([[3, 7], [9, 1]])

In [24]:
print(np.sort(arr, axis=0))

[[3 1]
 [9 7]]


In [25]:
arr = np.array([[4, 2, 6], [5, 6, 2], [1, 3, 5]])

In [26]:
print(np.sort(arr, axis=0))

[[1 2 2]
 [4 3 5]
 [5 6 6]]


In [27]:
print(np.sort(arr, axis=1))

[[2 4 6]
 [2 5 6]
 [1 3 5]]


In [28]:
print(np.sort(arr))

[[2 4 6]
 [2 5 6]
 [1 3 5]]


In [32]:
# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt)


print (a)
print(np.sort(a, order = 'name'))

[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


#### np.argsort()

In [33]:
x = np.array([3, 1, 2])

In [34]:
x

array([3, 1, 2])

In [35]:
y = np.argsort(x)

In [36]:
y

array([1, 2, 0], dtype=int64)

In [37]:
x[y]

array([1, 2, 3])

#### lexsort

In [38]:
nm = ('raju', 'anil', 'ravi', 'amar')

In [39]:
dv = ('f.y', 's.y', 's.y', 'f.y')

In [40]:
ind = np.lexsort((dv, nm))

In [41]:
ind

array([3, 1, 0, 2], dtype=int64)

In [46]:
print([nm[i] + " from " + dv[i] for i in ind])

['amar from f.y', 'anil from s.y', 'raju from f.y', 'ravi from s.y']


In [47]:
ind = np.lexsort((nm, dv))

In [48]:
ind

array([3, 0, 1, 2], dtype=int64)