In [3]:
l = [1, 2]

In [4]:
id(l)

2653203718272

In [5]:
l.append(3)

In [6]:
id(l)

2653203718272

In [9]:
s = "hello"

In [10]:
id(s)

2653199366960

In [11]:
s = s + " world"

In [12]:
id(s)

2653203683952

In [13]:
l = range(4)

In [14]:
type(l)

range

In [15]:
l = list(range(4))

In [16]:
type (l)

list

In [17]:
l = [1, 2, 3, 4]

In [18]:
for element in l:
    print(element)

1
2
3
4


In [20]:
l = [element*2 for element in l]

In [21]:
l

[2, 4, 6, 8]

In [22]:
l = [1, 2, 3] * 2

In [23]:
l

[1, 2, 3, 1, 2, 3]

### Size comparision for Numpy arr and list

In [33]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [34]:
import sys

In [35]:
sys.getsizeof(l)

216

In [36]:
import numpy as np

In [37]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [38]:
sys.getsizeof(a)

192

### Ways to create Numpy Array

In [39]:
import numpy as np

In [40]:
a = np.arange(5)

In [41]:
a

array([0, 1, 2, 3, 4])

##### NP arrays have got 0 based indexing same as that of the python list

In [44]:
l = [1,2,3]
a = np.array(l)

In [45]:
a

array([1, 2, 3])

In [46]:
a = np.array([(1,2,3), (4,5,6)])

In [47]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a = np.zeros((2, 3))

In [50]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
a = np.ones((2, 3))

In [52]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
a = np.empty((2, 3))

In [54]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
a = np.full((2, 3), 5)

In [56]:
a

array([[5, 5, 5],
       [5, 5, 5]])

In [57]:
a = np.random.random((2, 2))

In [58]:
a

array([[0.93013738, 0.55778578],
       [0.79032909, 0.10599809]])

### NP Dim

In [59]:
a = np.array(3)

In [60]:
a

array(3)

In [61]:
a.ndim

0

In [62]:
a = np.array([1,2,3,4])

In [63]:
a

array([1, 2, 3, 4])

In [64]:
a.ndim

1

In [65]:
a = np.array([[1,2],[3,4]])

In [66]:
a

array([[1, 2],
       [3, 4]])

In [67]:
a.ndim

2

## NP array property

In [77]:
a = np.array([[10, 20, 30],[23, 40, 50]])

In [78]:
# shape: 
a.shape

(2, 3)

In [79]:
# size
a.size

6

In [80]:
# dtype
a.dtype

dtype('int32')

In [81]:
# itemsize
a.itemsize

4